# Services that will be run regardless of environment and will not be built locally as part of development.
services:
  s3:
    image: minio/minio:latest
    hostname: nmcp-s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
    volumes:
      - s3:/data
    command: [ "server", "--console-address", ":9001", "/data" ]
    networks:
      - back_tier
    restart: unless-stopped

volumes:
  s3:

networks:
  back_tier:
